[options]
library = "Aravis"
version = "0.8"
min_cfg_version = "0.8"
girs_dir = "../gir-files"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
	"Aravis.AcquisitionMode",
	"Aravis.Auto",
	#"Aravis.Buffer",
	"Aravis.BufferPayloadType",
	"Aravis.BufferStatus",
	#"Aravis.Camera",
	#"Aravis.ChunkParser",
	#"Aravis.ChunkParserError",
	"Aravis.DebugLevel",
	#"Aravis.Device",
	"Aravis.DomCharacterData",
	"Aravis.DomDocument",
	"Aravis.DomDocumentCreateFunction",
	"Aravis.DomDocumentFragment",
	"Aravis.DomElement",
	"Aravis.DomNamedNodeMap",
	"Aravis.DomNode",
	"Aravis.DomNodeList",
	"Aravis.DomNodeType",
	"Aravis.DomText",
	"Aravis.Evaluator",
	#"Aravis.FakeCamera",
	"Aravis.FakeCameraFillPattern",
	"Aravis.FakeDevice",
	"Aravis.FakeInterface",
	"Aravis.FakeStream",
	"Aravis.Gc",
	"Aravis.GcAccessMode",
	#"Aravis.GcBoolean",
	"Aravis.GcCachable",
	"Aravis.GcCategory",
	"Aravis.GcCommand",
	"Aravis.GcConverter",
	"Aravis.GcConverterNode",
	"Aravis.GcEnumEntry",
	"Aravis.GcEnumeration",
	"Aravis.GcError",
	#"Aravis.GcFeatureNode",
	"Aravis.GcFloat",
	"Aravis.GcFloatNode",
	"Aravis.GcFloatRegNode",
	"Aravis.GcGroupNode",
	"Aravis.GcIndexNode",
	"Aravis.GcIntConverterNode",
	"Aravis.GcIntRegNode",
	"Aravis.GcIntSwissKnifeNode",
	"Aravis.GcInteger",
	"Aravis.GcIntegerNode",
	"Aravis.GcInvalidatorNode",
	"Aravis.GcIsLinear",
	"Aravis.GcMaskedIntRegNode",
	"Aravis.GcNameSpace",
	"Aravis.GcNode",
	"Aravis.GcPort",
	"Aravis.GcPropertyNode",
	"Aravis.GcPropertyNodeType",
	"Aravis.GcRegister",
	"Aravis.GcRegisterDescriptionNode",
	"Aravis.GcRegisterNode",
	"Aravis.GcSelector",
	"Aravis.GcSignedness",
	"Aravis.GcString",
	"Aravis.GcStringRegNode",
	"Aravis.GcStructEntryNode",
	"Aravis.GcStructRegNode",
	"Aravis.GcSwissKnife",
	"Aravis.GcSwissKnifeNode",
	"Aravis.GcValueIndexedNode",
	#"Aravis.GvDevice",
	"Aravis.GvFakeCamera",
	"Aravis.GvInterface",
	"Aravis.GvStream",
	"Aravis.GvStreamOption",
	"Aravis.GvStreamPacketResend",
	"Aravis.GvStreamSocketBuffer",
	"Aravis.Interface",
	#"Aravis.PixelFormat",
	"Aravis.RegisterCachePolicy",
	"Aravis.Stream",
	"Aravis.StreamCallback",
	"Aravis.UvDevice",
	"Aravis.UvInterface",
	"Aravis.UvStream",
	"Aravis.XmlSchema",
	"Aravis.XmlSchemaError",
	#"Aravis.DebugCategory",
	#"Aravis.GcFloatInterface",
	#"Aravis.GcIntegerInterface",
	#"Aravis.GcRegisterInterface",
	#"Aravis.GcSelectorInterface",
	#"Aravis.GcStringInterface",
	#"Aravis.Zip",
	#"Aravis.ZipFile",
]

builder = [
	"Aravis.CameraBuilder",
	"Aravis.ChunkParserBuilder",
	"Aravis.GcPropertyNodeBuilder",
	"Aravis.GvFakeCameraBuilder",
	"Aravis.GvStreamBuilder",
	"Aravis.StreamBuilder",
]

manual = [
	"GLib.Array",
	"GLib.AsyncQueue",
	"GLib.TimeVal",
	"GLib.BookmarkFile",
	"GLib.Error",
	"GLib.ByteArray",
	"GLib.Bytes",
	"GLib.Checksum",
	"GLib.Cond",
	"GLib.Data",
	"GLib.Date",
	"GLib.DateTime",
	"GLib.DestroyNotify",
	"GLib.TimeZone",
	"GLib.DebugKey",
	"GLib.Dir",
	"GLib.HashTable",
	"GLib.HashTableIter",
	"GLib.Hmac",
	"GLib.Hook",
	"GLib.HookList",
	"GLib.IConv",
	"GLib.IOFuncs",
	"GLib.String",
	"GLib.IOChannel",
	"GLib.Source",
	"GLib.KeyFile",
	"GLib.List",
	"GLib.LogField",
	"GLib.MainContext",
	"GLib.PollFD",
	"GLib.SourceFuncs",
	"GLib.MainLoop",
	"GLib.MappedFile",
	"GLib.MarkupParseContext",
	"GLib.MarkupParser",
	"GLib.MatchInfo",
	#"GLib.Regex",
	"GLib.MemVTable",
	"GLib.Node",
	"GLib.Once",
	"GLib.OptionContext",
	"GLib.OptionGroup",
	"GLib.OptionEntry",
	"GLib.PatternSpec",
	"GLib.Private",
	"GLib.PtrArray",
	"GLib.Quark",
	"GLib.Queue",
	"GLib.RWLock",
	"GLib.Rand",
	"GLib.RecMutex",
	"GLib.SList",
	"GLib.ScannerConfig",
	"GLib.Scanner",
	"GLib.SequenceIter",
	"GLib.Sequence",
	"GLib.SourceCallbackFuncs",
	"GLib.SourcePrivate",
	"GLib.StatBuf",
	"GLib.StringChunk",
	"GLib.TestCase",
	"GLib.TestConfig",
	"GLib.TestLogBuffer",
	"GLib.TestLogMsg",
	"GLib.TestSuite",
	"GLib.Thread",
	"GLib.ThreadPool",
	"GLib.Timer",
	"GLib.TrashStack",
	"GLib.Tree",
	"GLib.Variant",
	"GLib.VariantType",
	"GLib.VariantIter",
	"GLib.VariantBuilder",
	"GLib.VariantDict",
	"GObject.TypeClass",
	"GObject.Binding",
	"GObject.Object",
	"GObject.Value",
	"GObject.Closure",
	"GObject.TypeInstance",
	"GObject.CClosure",
	"GObject.ClosureNotifyData",
	"GObject.EnumValue",
	"GObject.EnumClass",
	"GObject.FlagsValue",
	"GObject.FlagsClass",
	"GObject.InitiallyUnowned",
	"GObject.ObjectConstructParam",
	"GObject.ParamSpec",
	"GObject.InitiallyUnownedClass",
	"GObject.TypeInterface",
	"GObject.InterfaceInfo",
	"GObject.Parameter",
	"GObject.ObjectClass",
	"GObject.ParamSpecBoolean",
	"GObject.ParamSpecBoxed",
	"GObject.ParamSpecChar",
	"GObject.ParamSpecClass",
	"GObject.ParamSpecDouble",
	"GObject.ParamSpecEnum",
	"GObject.ParamSpecFlags",
	"GObject.ParamSpecFloat",
	"GObject.ParamSpecGType",
	"GObject.ParamSpecInt",
	"GObject.ParamSpecInt64",
	"GObject.ParamSpecLong",
	"GObject.ParamSpecObject",
	"GObject.ParamSpecOverride",
	"GObject.ParamSpecParam",
	"GObject.ParamSpecPointer",
	"GObject.ParamSpecPool",
	"GObject.ParamSpecString",
	"GObject.ParamSpecTypeInfo",
	"GObject.ParamSpecUChar",
	"GObject.ParamSpecUInt",
	"GObject.ParamSpecUInt64",
	"GObject.ParamSpecULong",
	"GObject.ParamSpecUnichar",
	"GObject.ParamSpecValueArray",
	"GObject.ParamSpecVariant",
	"GObject.SignalInvocationHint",
	"GObject.SignalQuery",
	"GObject.TypeFundamentalInfo",
	"GObject.TypeValueTable",
	"GObject.TypeInfo",
	"GObject.TypePlugin",
	"GObject.TypeModule",
	"GObject.TypeModuleClass",
	"GObject.TypePluginClass",
	"GObject.TypeQuery",
	"GObject.ValueArray",
	"GObject.WeakRef",
	"Gio.Action",
	"Gio.SimpleAction",
	"Gio.ActionEntry",
	"Gio.ActionGroup",
	"Gio.ActionGroupInterface",
	"Gio.ActionInterface",
	"Gio.ActionMap",
	"Gio.ActionMapInterface",
	"Gio.AppInfo",
	"Gio.AppLaunchContext",
	"Gio.Cancellable",
	"Gio.AsyncResult",
	"Gio.Icon",
	"Gio.File",
	"Gio.AppInfoIface",
	"Gio.AppInfoMonitor",
	"Gio.AppLaunchContextPrivate",
	"Gio.AppLaunchContextClass",
	"Gio.Application",
	"Gio.DBusConnection",
	"Gio.Notification",
	"Gio.ApplicationPrivate",
	"Gio.ApplicationCommandLine",
	"Gio.ApplicationClass",
	"Gio.InputStream",
	"Gio.ApplicationCommandLinePrivate",
	"Gio.ApplicationCommandLineClass",
	#"Gio.AsyncInitable",
	#"Gio.AsyncInitableIface",
	"Gio.AsyncResultIface",
	"Gio.Seekable",
	"Gio.BufferedInputStream",
	"Gio.FilterInputStream",
	"Gio.BufferedInputStreamPrivate",
	"Gio.FilterInputStreamClass",
	"Gio.BufferedInputStreamClass",
	"Gio.OutputStream",
	"Gio.BufferedOutputStream",
	"Gio.FilterOutputStream",
	"Gio.BufferedOutputStreamPrivate",
	"Gio.FilterOutputStreamClass",
	"Gio.BufferedOutputStreamClass",
	"Gio.LoadableIcon",
	"Gio.BytesIcon",
	"Gio.CancellablePrivate",
	"Gio.CancellableClass",
	"Gio.Converter",
	"Gio.CharsetConverter",
	"Gio.CharsetConverterClass",
	"Gio.ConverterIface",
	"Gio.PollableInputStream",
	"Gio.ConverterInputStream",
	"Gio.ConverterInputStreamPrivate",
	"Gio.ConverterInputStreamClass",
	"Gio.PollableOutputStream",
	"Gio.ConverterOutputStream",
	"Gio.ConverterOutputStreamPrivate",
	"Gio.ConverterOutputStreamClass",
	"Gio.Credentials",
	"Gio.CredentialsClass",
	"Gio.RemoteActionGroup",
	"Gio.DBusActionGroup",
	"Gio.DBusAnnotationInfo",
	"Gio.DBusArgInfo",
	"Gio.DBusAuthObserver",
	"Gio.IOStream",
	"Gio.UnixFDList",
	"Gio.MenuModel",
	"Gio.DBusInterfaceInfo",
	"Gio.DBusInterfaceVTable",
	"Gio.DBusSubtreeVTable",
	"Gio.DBusMessage",
	"Gio.DBusErrorEntry",
	"Gio.DBusObject",
	"Gio.DBusInterface",
	"Gio.DBusInterfaceIface",
	"Gio.DBusMethodInfo",
	"Gio.DBusSignalInfo",
	"Gio.DBusPropertyInfo",
	"Gio.DBusMethodInvocation",
	"Gio.DBusInterfaceSkeleton",
	"Gio.DBusInterfaceSkeletonPrivate",
	"Gio.DBusInterfaceSkeletonClass",
	"Gio.DBusMenuModel",
	"Gio.DBusNodeInfo",
	"Gio.DBusObjectIface",
	"Gio.DBusObjectManager",
	"Gio.DBusObjectManagerClient",
	"Gio.DBusObjectManagerClientPrivate",
	"Gio.DBusObjectProxy",
	"Gio.DBusProxy",
	"Gio.DBusObjectManagerClientClass",
	"Gio.DBusObjectManagerIface",
	"Gio.DBusObjectManagerServer",
	"Gio.DBusObjectSkeleton",
	"Gio.DBusObjectManagerServerPrivate",
	"Gio.DBusObjectManagerServerClass",
	"Gio.DBusObjectProxyPrivate",
	"Gio.DBusObjectProxyClass",
	"Gio.DBusObjectSkeletonPrivate",
	"Gio.DBusObjectSkeletonClass",
	"Gio.DBusProxyPrivate",
	"Gio.DBusProxyClass",
	"Gio.DBusServer",
	"Gio.DataInputStream",
	"Gio.DataInputStreamPrivate",
	"Gio.DataInputStreamClass",
	"Gio.DataOutputStream",
	"Gio.DataOutputStreamPrivate",
	"Gio.DataOutputStreamClass",
	"Gio.DatagramBased",
	"Gio.InputMessage",
	"Gio.OutputMessage",
	"Gio.DatagramBasedInterface",
	"Gio.DesktopAppInfo",
	"Gio.DesktopAppInfoClass",
	"Gio.DesktopAppInfoLookup",
	"Gio.DesktopAppInfoLookupIface",
	"Gio.Drive",
	"Gio.MountOperation",
	"Gio.Volume",
	"Gio.DriveIface",
	"Gio.DtlsConnection",
	"Gio.DtlsClientConnection",
	"Gio.SocketConnectable",
	"Gio.DtlsClientConnectionInterface",
	"Gio.TlsCertificate",
	"Gio.TlsDatabase",
	"Gio.TlsInteraction",
	"Gio.DtlsConnectionInterface",
	"Gio.DtlsServerConnection",
	"Gio.DtlsServerConnectionInterface",
	"Gio.Emblem",
	"Gio.EmblemClass",
	"Gio.EmblemedIcon",
	"Gio.EmblemedIconPrivate",
	"Gio.EmblemedIconClass",
	"Gio.FileIOStream",
	"Gio.FileOutputStream",
	"Gio.FileEnumerator",
	"Gio.Mount",
	"Gio.FileMonitor",
	"Gio.FileInfo",
	"Gio.FileAttributeInfoList",
	"Gio.FileInputStream",
	"Gio.FileAttributeInfo",
	"Gio.FileAttributeMatcher",
	"Gio.FileDescriptorBased",
	"Gio.FileDescriptorBasedIface",
	"Gio.FileEnumeratorPrivate",
	"Gio.FileEnumeratorClass",
	"Gio.FileIOStreamPrivate",
	"Gio.IOStreamClass",
	"Gio.FileIOStreamClass",
	"Gio.FileIcon",
	"Gio.FileIconClass",
	"Gio.FileIface",
	"Gio.FileInfoClass",
	"Gio.FileInputStreamPrivate",
	"Gio.InputStreamClass",
	"Gio.FileInputStreamClass",
	"Gio.FileMonitorPrivate",
	"Gio.FileMonitorClass",
	"Gio.FileOutputStreamPrivate",
	"Gio.OutputStreamClass",
	"Gio.FileOutputStreamClass",
	"Gio.FilenameCompleter",
	"Gio.FilenameCompleterClass",
	"Gio.IOExtension",
	"Gio.IOExtensionPoint",
	"Gio.IOModule",
	"Gio.IOModuleClass",
	"Gio.IOModuleScope",
	"Gio.IOSchedulerJob",
	"Gio.IOStreamPrivate",
	"Gio.IOStreamAdapter",
	"Gio.IconIface",
	"Gio.InetAddress",
	"Gio.InetAddressPrivate",
	"Gio.InetAddressClass",
	"Gio.InetAddressMask",
	"Gio.InetAddressMaskPrivate",
	"Gio.InetAddressMaskClass",
	"Gio.SocketAddress",
	"Gio.InetSocketAddress",
	"Gio.InetSocketAddressPrivate",
	"Gio.SocketAddressClass",
	"Gio.InetSocketAddressClass",
	#"Gio.Initable",
	#"Gio.InitableIface",
	"Gio.InputVector",
	"Gio.SocketControlMessage",
	"Gio.InputStreamPrivate",
	"Gio.ListModel",
	"Gio.ListModelInterface",
	"Gio.ListStore",
	"Gio.ListStoreClass",
	"Gio.LoadableIconIface",
	"Gio.MemoryInputStream",
	"Gio.MemoryInputStreamPrivate",
	"Gio.MemoryInputStreamClass",
	"Gio.MemoryOutputStream",
	"Gio.MemoryOutputStreamPrivate",
	"Gio.MemoryOutputStreamClass",
	"Gio.Menu",
	"Gio.MenuItem",
	"Gio.MenuAttributeIter",
	"Gio.MenuAttributeIterPrivate",
	"Gio.MenuAttributeIterClass",
	"Gio.MenuLinkIter",
	"Gio.MenuLinkIterPrivate",
	"Gio.MenuLinkIterClass",
	"Gio.MenuModelPrivate",
	"Gio.MenuModelClass",
	"Gio.MountIface",
	"Gio.MountOperationPrivate",
	"Gio.MountOperationClass",
	"Gio.NativeSocketAddress",
	"Gio.VolumeMonitor",
	"Gio.NativeVolumeMonitor",
	"Gio.VolumeMonitorClass",
	"Gio.NativeVolumeMonitorClass",
	"Gio.NetworkAddress",
	"Gio.NetworkAddressPrivate",
	"Gio.NetworkAddressClass",
	"Gio.NetworkMonitor",
	"Gio.NetworkMonitorInterface",
	"Gio.NetworkService",
	"Gio.NetworkServicePrivate",
	"Gio.NetworkServiceClass",
	"Gio.OutputVector",
	"Gio.OutputStreamPrivate",
	"Gio.Permission",
	"Gio.PermissionPrivate",
	"Gio.PermissionClass",
	"Gio.PollableInputStreamInterface",
	"Gio.PollableOutputStreamInterface",
	"Gio.PropertyAction",
	"Gio.Proxy",
	"Gio.ProxyAddress",
	"Gio.ProxyAddressPrivate",
	"Gio.ProxyAddressClass",
	"Gio.ProxyResolver",
	"Gio.SocketAddressEnumerator",
	"Gio.ProxyAddressEnumeratorPrivate",
	"Gio.ProxyAddressEnumerator",
	"Gio.SocketAddressEnumeratorClass",
	"Gio.ProxyAddressEnumeratorClass",
	"Gio.ProxyInterface",
	"Gio.ProxyResolverInterface",
	"Gio.RemoteActionGroupInterface",
	"Gio.Resolver",
	"Gio.SrvTarget",
	"Gio.ResolverPrivate",
	"Gio.ResolverClass",
	"Gio.Resource",
	"Gio.SeekableIface",
	"Gio.Settings",
	"Gio.SettingsSchema",
	"Gio.SettingsBackend",
	"Gio.SettingsPrivate",
	"Gio.SettingsBackendPrivate",
	"Gio.SettingsBackendClass",
	"Gio.SettingsClass",
	"Gio.SettingsSchemaKey",
	"Gio.SettingsSchemaSource",
	"Gio.SimpleActionGroup",
	"Gio.SimpleActionGroupPrivate",
	"Gio.SimpleActionGroupClass",
	"Gio.SimpleAsyncResult",
	"Gio.SimpleAsyncResultClass",
	"Gio.SimpleIOStream",
	"Gio.SimplePermission",
	"Gio.SimpleProxyResolver",
	"Gio.SimpleProxyResolverPrivate",
	"Gio.SimpleProxyResolverClass",
	"Gio.Socket",
	"Gio.SocketConnection",
	"Gio.SocketPrivate",
	"Gio.SocketClass",
	"Gio.SocketClient",
	"Gio.SocketClientPrivate",
	"Gio.SocketClientClass",
	"Gio.SocketConnectableIface",
	"Gio.SocketConnectionPrivate",
	"Gio.SocketConnectionClass",
	"Gio.SocketControlMessagePrivate",
	"Gio.SocketControlMessageClass",
	"Gio.SocketListener",
	"Gio.SocketListenerPrivate",
	"Gio.SocketListenerClass",
	"Gio.SocketService",
	"Gio.SocketServicePrivate",
	"Gio.SocketServiceClass",
	"Gio.StaticResource",
	"Gio.Subprocess",
	"Gio.SubprocessLauncher",
	"Gio.Task",
	"Gio.TaskClass",
	"Gio.TcpConnection",
	"Gio.TcpConnectionPrivate",
	"Gio.TcpConnectionClass",
	"Gio.TcpWrapperConnection",
	"Gio.TcpWrapperConnectionPrivate",
	"Gio.TcpWrapperConnectionClass",
	"Gio.TestDBus",
	"Gio.ThemedIcon",
	"Gio.ThemedIconClass",
	"Gio.ThreadedSocketServicePrivate",
	"Gio.ThreadedSocketService",
	"Gio.ThreadedSocketServiceClass",
	"Gio.TlsBackend",
	"Gio.TlsBackendInterface",
	"Gio.TlsCertificatePrivate",
	"Gio.TlsCertificateClass",
	"Gio.TlsConnection",
	"Gio.TlsClientConnection",
	"Gio.TlsClientConnectionInterface",
	"Gio.TlsConnectionPrivate",
	"Gio.TlsConnectionClass",
	"Gio.TlsDatabasePrivate",
	"Gio.TlsDatabaseClass",
	"Gio.TlsFileDatabase",
	"Gio.TlsFileDatabaseInterface",
	"Gio.TlsPassword",
	"Gio.TlsInteractionPrivate",
	"Gio.TlsInteractionClass",
	"Gio.TlsPasswordPrivate",
	"Gio.TlsPasswordClass",
	"Gio.TlsServerConnection",
	"Gio.TlsServerConnectionInterface",
	"Gio.UnixConnection",
	"Gio.UnixConnectionPrivate",
	"Gio.UnixConnectionClass",
	"Gio.UnixCredentialsMessage",
	"Gio.UnixCredentialsMessagePrivate",
	"Gio.UnixCredentialsMessageClass",
	"Gio.UnixFDListPrivate",
	"Gio.UnixFDListClass",
	"Gio.UnixFDMessage",
	"Gio.UnixFDMessagePrivate",
	"Gio.UnixFDMessageClass",
	"Gio.UnixInputStream",
	"Gio.UnixInputStreamPrivate",
	"Gio.UnixInputStreamClass",
	"Gio.UnixMountEntry",
	"Gio.UnixMountMonitor",
	"Gio.UnixMountMonitorClass",
	"Gio.UnixMountPoint",
	"Gio.UnixOutputStream",
	"Gio.UnixOutputStreamPrivate",
	"Gio.UnixOutputStreamClass",
	"Gio.UnixSocketAddress",
	"Gio.UnixSocketAddressPrivate",
	"Gio.UnixSocketAddressClass",
	"Gio.Vfs",
	"Gio.VfsClass",
	"Gio.VolumeIface",
	"Gio.ZlibCompressor",
	"Gio.ZlibCompressorClass",
	"Gio.ZlibDecompressor",
	"Gio.ZlibDecompressorClass",
]

[[object]]
name = "Aravis.Buffer"
status = "generate"
	[[object.function]]
	name = "new_full"
	ignore = true
	[[object.function]]
	name = "get_data"
	ignore = true

[[object]]
name = "Aravis.Camera"
status = "generate"
	[[object.function]]
	name = "create_stream"
	ignore = true
	[[object.function]]
	name = "gv_get_packet_size"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "check_status"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_boolean"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_boolean_gi"
	ignore = true
	[[object.function]]
	name = "get_chunk_mode"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_chunk_state"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_payload"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "gv_get_packet_size"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_binning_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_exposure_auto_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_exposure_time_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_feature_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_frame_rate_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_gain_auto_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_gain_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "uv_get_bandwidth"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "name"
	return = { use_return_for_result = true }

[[object]]
name = "Aravis.Device"
status = "generate"
	[[object.function]]
	name = "create_stream"
	ignore = true
	[[object.function]]
	name = "get_boolean_feature_value"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_boolean_feature_value_gi"
	ignore = true
	[[object.function]]
	name = "is_feature_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "read_memory"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "read_register"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "write_memory"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "write_register"
	return = { use_return_for_result = true }

[[object]]
name = "Aravis.FakeCamera"
status = "generate"
	[[object.function]]
	name = "set_fill_pattern"
	ignore = true

[[object]]
name = "Aravis.GcBoolean"
status = "generate"
	[[object.function]]
	name = "get_value"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "get_value_gi"
	ignore = true

[[object]]
name = "Aravis.GcFeatureNode"
status = "generate"
	[[object.function]]
	name = "is_available"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_implemented"
	return = { use_return_for_result = true }
	[[object.function]]
	name = "is_locked"
	return = { use_return_for_result = true }

[[object]]
name = "Aravis.GvDevice"
status = "generate"
	[[object.function]]
	name = "get_packet_size"
	return = { use_return_for_result = true }

[[object]]
name = "Aravis.PixelFormat"
status = "manual"
conversion_type = "scalar"
